"""initial schema

Revision ID: 4c661df69e4c
Revises: 
Create Date: 2026-07-19 19:21:48.303628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c661df69e4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_item',
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(length=20), nullable=True),
    sa.Column('channel_account_id', sa.Integer(), nullable=True),
    sa.Column('channel_message_id', sa.String(length=120), nullable=True),
    sa.Column('sender_email', sa.String(length=160), nullable=True),
    sa.Column('sender_name', sa.String(length=160), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('route', sa.String(length=24), nullable=False),
    sa.Column('bucket', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('decision', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('inquiry_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=12), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_account.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiry.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_triage_item_channel_message_id', 'triage_item', ['channel_message_id'], unique=False)
    op.create_index('ix_triage_item_seller_bucket_status', 'triage_item', ['seller_id', 'bucket', 'status'], unique=False)
    op.add_column('customer', sa.Column('lifecycle_stage', sa.String(length=32), nullable=False))
    op.add_column('customer', sa.Column('intent_level', sa.String(length=16), nullable=False))
    op.add_column('customer', sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))
    op.add_column('customer', sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customer', sa.Column('takeover_status', sa.String(length=24), nullable=False))
    op.create_index('ix_customer_seller_lifecycle', 'customer', ['seller_id', 'lifecycle_stage'], unique=False)
    op.add_column('inquiry', sa.Column('lead_type', sa.String(length=24), nullable=False))
    op.add_column('inquiry', sa.Column('contact_source', sa.String(length=40), nullable=True))
    op.add_column('inquiry', sa.Column('lifecycle_stage', sa.String(length=32), nullable=False))
    op.add_column('inquiry', sa.Column('intent_level', sa.String(length=16), nullable=False))
    op.add_column('inquiry', sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))
    op.add_column('inquiry', sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inquiry', sa.Column('takeover_required', sa.Boolean(), nullable=False))
    op.add_column('inquiry', sa.Column('takeover_reason', sa.String(length=80), nullable=True))
    op.create_index('ix_inquiry_seller_lifecycle', 'inquiry', ['seller_id', 'lifecycle_stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inquiry_seller_lifecycle', table_name='inquiry')
    op.drop_column('inquiry', 'takeover_reason')
    op.drop_column('inquiry', 'takeover_required')
    op.drop_column('inquiry', 'next_followup_at')
    op.drop_column('inquiry', 'tags')
    op.drop_column('inquiry', 'intent_level')
    op.drop_column('inquiry', 'lifecycle_stage')
    op.drop_column('inquiry', 'contact_source')
    op.drop_column('inquiry', 'lead_type')
    op.drop_index('ix_customer_seller_lifecycle', table_name='customer')
    op.drop_column('customer', 'takeover_status')
    op.drop_column('customer', 'next_followup_at')
    op.drop_column('customer', 'tags')
    op.drop_column('customer', 'intent_level')
    op.drop_column('customer', 'lifecycle_stage')
    op.drop_index('ix_triage_item_seller_bucket_status', table_name='triage_item')
    op.drop_index('ix_triage_item_channel_message_id', table_name='triage_item')
    op.drop_table('triage_item')
    # ### end Alembic commands ###
